name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format code
        run: |
          cargo fmt
          git config --global user.name "Github Actions"
          git commit -am "chore: cargo fmt"
          git push origin main
